### ISSUE TITLE
Multiple tag files

### ISSUE THREAD

**Issue by akemrir** [deoplete-plugins/deoplete-tag#1]
hi,
how can I define multiple tag files to be loaded by this plugin?

I am using Universal-ctags on linux.
My resulting tag files are sorted.

`tags` file is ignored too.

**Comment by akemrir** [comment]
Ok, I have debugged this. And it looks it uses all of my files.
But ignores `User` for example when searching for candidates while typing `us`

**Comment by akemrir** [comment]
I think I`ve found it. It needs sort yes on ctags, instead of foldcase sorting.
Then it suggest tags.

**Comment by blueyed** [comment]
@akemrir 
Since you've looked at the code: do you think it could help with a message in case the file is not sorted?
(IIRC Vim is able to detect/report this itself when using tags file)

(not using the plugin myself)

**Comment by akemrir** [comment]
Yes, message about not proper sorting would we awesome. It took some time to find this `fix`.
Of course info in readme could be useful too.

**Comment by blueyed** [comment]
@akemrir 
In case it wasn't clear: I've meant you to create a PR based on your findings when you've investigated.. :)
