### ISSUE TITLE
Issue with members

### ISSUE THREAD

**Issue by sl8vz** [deoplete-plugins/deoplete-tag#2]
Using neovim v0.4.3
Default deoplete config
```
let g:deoplete#enable_at_startup = 1
let g:deoplete#tag#cache_limit_size = 50000000
```
Global or functions completion are correctly using the tag file with complete header and file source.
However as soon as I try to complete a struct member for example I don't have suggestions from tags anymore but only members found in the current file. If I try omnicompletion (C-x C-o) I get all members from tag file.

tag file generared from https://github.com/ggreer/the_silver_searcher

![deoplete_complete](https://user-images.githubusercontent.com/37440531/84254262-49d96880-ab11-11ea-979a-b07f3b5a79e9.png)

![omnicomplete](https://user-images.githubusercontent.com/37440531/84254301-55c52a80-ab11-11ea-995e-825d9894720e.png)

[tags.zip](https://github.com/deoplete-plugins/deoplete-tag/files/4757661/tags.zip)

**Comment by Shougo** [comment]
Thank you for the report.

I get the problem.

This feature is really needed?  I think you should use LSP completion instead.

**Comment by sl8vz** [comment]
Hi @Shougo ,

Actually LSP would rely on clang based tools and the need of a JSON compilation database.
While it can be pretty straighforward to generate when using CMake or clang toolchain, it's not the case with classic Make/gcc projects (which I'm mostly working on)

So in my case ctags based completion is by far the most convenient which doesn't require any configuration. I can jump on any project, generate the tags (even for bash scriptss.... ) and I'm good to go. For sure it's not 100% perfect as it doesn't know actual defines used at compilation time but it does the job 99% of the time.

Assuming that omnicompletion can suggest members correctly using the tag file is there something really blocking to do it for deoplete ?

**Comment by sl8vz** [comment]
And by the way I'd be happy to contribute if you think the change is possible.

**Comment by Shougo** [comment]
OK.  But the change is not possible.

You should call the omnifunc from deoplete instead.

```vim
set completeopt+=noselect
call deoplete#custom#option('omni_patterns', {
\ 'c': ['[^. *\t]\%(\.\|->\)\w*',
\ 'cpp': ['[^. *\t]\%(\.\|->\)\w*', '[a-zA-Z_]\w*::'],
\})
```

**Comment by sl8vz** [comment]
Thanks @Shougo it fixes my problem.
